// ─── Mock User ───────────────────────────────────────────────────────────────
export const mockUser = {
  nome: "Maria",
  anno_nascita: 1958,
  streak: 5,
  esercizi_totali: 23,
  score_settimana: 4,
};

// ─── Mock Categorie ───────────────────────────────────────────────────────────
export const mockCategorie = [
  { id: "memoria",    nome: "Memoria",    icona: "brain",  colore: "#2563EB", descrizione: "Ricorda, memorizza, richiama" },
  { id: "attenzione", nome: "Attenzione", icona: "target", colore: "#7C3AED", descrizione: "Concentrati, osserva, reagisci" },
  { id: "linguaggio", nome: "Linguaggio", icona: "chat",   colore: "#16A34A", descrizione: "Parole, frasi, significati" },
  { id: "esecutive",     nome: "Esecutive",     icona: "puzzle", colore: "#D97706", descrizione: "Pianifica, organizza, decidi" },
  { id: "visuospaziali", nome: "Visuospaziali", icona: "eye",    colore: "#0F766E", descrizione: "Percepisci, orienta, visualizza" },
];

// ─── Mock Esercizi ────────────────────────────────────────────────────────────
export const mockEsercizi = [
  {
    id: "sequence-tap-numeri",
    categoria_id: "memoria",
    titolo: "Sequenza di Numeri",
    descrizione: "Osserva la sequenza di numeri e riproducila nell'ordine corretto.",
    difficolta: "facile",
    livello: 1,
    famiglia: "sequence_tap",
    durata_stimata: 60,
    beneficio: "Allena la memoria di lavoro verbale e visuo-sequenziale.",
    config: {
      game: "sequence_tap",
      stimulusType: "numeri",
    },
  },
  {
    id: "sequence-tap-parole",
    categoria_id: "memoria",
    titolo: "Sequenza di Parole",
    descrizione: "Osserva la sequenza di parole e riproducila nell'ordine corretto.",
    difficolta: "facile",
    livello: 1,
    famiglia: "sequence_tap",
    durata_stimata: 60,
    beneficio: "Allena la memoria di lavoro verbale.",
    config: {
      game: "sequence_tap",
      stimulusType: "parole",
    },
  },
  {
    id: "sequence-tap-immagini",
    categoria_id: "memoria",
    titolo: "Sequenza di Immagini",
    descrizione: "Osserva la sequenza di immagini e riproducila nell'ordine corretto.",
    difficolta: "facile",
    livello: 1,
    famiglia: "sequence_tap",
    durata_stimata: 60,
    beneficio: "Allena la memoria visuo-sequenziale.",
    config: {
      game: "sequence_tap",
      stimulusType: "immagini",
    },
  },
  {
    id: "recall-grid-numeri",
    categoria_id: "memoria",
    titolo: "Griglia di Numeri",
    descrizione: "Osserva i numeri nella griglia e ricorda le loro posizioni.",
    difficolta: "facile",
    livello: 1,
    famiglia: "recall_grid",
    durata_stimata: 60,
    beneficio: "Allena la memoria visuospaziale a breve termine.",
    config: { game: "recall_grid", stimulusType: "numeri" },
  },
  {
    id: "recall-grid-parole",
    categoria_id: "memoria",
    titolo: "Griglia di Parole",
    descrizione: "Osserva le parole nella griglia e ricorda le loro posizioni.",
    difficolta: "facile",
    livello: 1,
    famiglia: "recall_grid",
    durata_stimata: 60,
    beneficio: "Allena la memoria visuospaziale e verbale.",
    config: { game: "recall_grid", stimulusType: "parole" },
  },
  // ── Nuove famiglie ────────────────────────────────────────────────────────
  {
    id: "sort-it-colore",
    categoria_id: "esecutive",
    titolo: "Sort It — Colori",
    descrizione: "Assegna le carte alle categorie giuste. La regola cambia!",
    difficolta: "facile",
    livello: 1,
    famiglia: "sort_it",
    durata_stimata: 60,
    beneficio: "Allena la flessibilità cognitiva e l'inibizione delle risposte automatiche.",
    config: { game: "sort_it", stimulusType: "colore" },
  },
  {
    id: "pasat-light-single",
    categoria_id: "attenzione",
    titolo: "PASAT — Cifre",
    descrizione: "Somma il numero corrente con quello precedente e tocca il risultato.",
    difficolta: "medio",
    livello: 1,
    famiglia: "pasat_light",
    durata_stimata: 60,
    beneficio: "Allena la memoria di lavoro aritmetica e l'attenzione sostenuta.",
    config: { game: "pasat_light", digitType: "single" },
  },
  {
    id: "updating-wm-numeri",
    categoria_id: "memoria",
    titolo: "Memoria in Aggiornamento",
    descrizione: "Tieni aggiornato il numero massimo nella sequenza.",
    difficolta: "medio",
    livello: 1,
    famiglia: "updating_wm",
    durata_stimata: 60,
    beneficio: "Allena la memoria di lavoro e la capacità di aggiornare le informazioni.",
    config: { game: "updating_wm", stimulusType: "numerici" },
  },
  {
    id: "memoria-lista-parole",
    categoria_id: "memoria",
    titolo: "Memoria Lista Parole",
    descrizione: "Memorizza la lista, poi riconosci le parole originali.",
    difficolta: "facile",
    livello: 1,
    famiglia: "memoria_lista",
    durata_stimata: 60,
    beneficio: "Allena la memoria verbale a lungo termine e il riconoscimento.",
    config: { game: "memoria_lista", stimulusType: "parole_non_correlate" },
  },
  {
    id: "memoria-prosa-narrativi",
    categoria_id: "memoria",
    titolo: "Memoria di Prosa",
    descrizione: "Leggi un breve racconto e rispondi a domande su di esso.",
    difficolta: "facile",
    livello: 1,
    famiglia: "memoria_di_prosa",
    durata_stimata: 60,
    beneficio: "Allena la comprensione e la memoria del testo.",
    config: { game: "memoria_di_prosa", textType: "narrativi" },
  },
  {
    id: "sart-cifre",
    categoria_id: "attenzione",
    titolo: "SART — Reazione",
    descrizione: "Tocca tutto tranne il numero 3! Reagisci velocemente.",
    difficolta: "facile",
    livello: 1,
    famiglia: "sart",
    durata_stimata: 60,
    beneficio: "Allena l'inibizione delle risposte e l'attenzione sostenuta.",
    config: { game: "sart" },
  },
  {
    id: "go-nogo-cromatico",
    categoria_id: "attenzione",
    titolo: "Go / No-Go Colori",
    descrizione: "Tocca se verde, aspetta se rosso. Reagisci al colore giusto!",
    difficolta: "facile",
    livello: 1,
    famiglia: "go_nogo",
    durata_stimata: 60,
    beneficio: "Allena l'inibizione e il controllo delle risposte impulsive.",
    config: { game: "go_nogo", stimulusType: "cromatico" },
  },
  {
    id: "simon-spaziale",
    categoria_id: "esecutive",
    titolo: "Simon Spaziale",
    descrizione: "Tocca la direzione della freccia, ignorando dove appare sullo schermo.",
    difficolta: "facile",
    livello: 1,
    famiglia: "simon",
    durata_stimata: 60,
    beneficio: "Allena il controllo dell'interferenza spaziale e la risoluzione del conflitto.",
    config: { game: "simon" },
  },
  {
    id: "task-switching-numeri",
    categoria_id: "esecutive",
    titolo: "Task Switching",
    descrizione: "Cambia regola ad ogni trial: pari/dispari oppure ≤5/>5.",
    difficolta: "medio",
    livello: 1,
    famiglia: "task_switching",
    durata_stimata: 60,
    beneficio: "Allena la flessibilità cognitiva e la capacità di cambiare strategia.",
    config: { game: "task_switching" },
  },
  {
    id: "dccs-light",
    categoria_id: "esecutive",
    titolo: "DCCS — Classifica Carte",
    descrizione: "Classifica le carte per colore, poi forma, poi numero.",
    difficolta: "facile",
    livello: 1,
    famiglia: "dccs_light",
    durata_stimata: 60,
    beneficio: "Allena la flessibilità cognitiva e la capacità di seguire regole.",
    config: { game: "dccs_light" },
  },
  {
    id: "mental-rotation-forme",
    categoria_id: "visuospaziali",
    titolo: "Rotazione Mentale",
    descrizione: "Le due figure sono uguali o specchiate?",
    difficolta: "facile",
    livello: 1,
    famiglia: "mental_rotation",
    durata_stimata: 60,
    beneficio: "Allena la rotazione mentale e la percezione spaziale.",
    config: { game: "mental_rotation", stimulusType: "forme" },
  },
  {
    id: "figure-ground-forme",
    categoria_id: "visuospaziali",
    titolo: "Figura e Sfondo",
    descrizione: "Trova il simbolo diverso nella griglia il più velocemente possibile.",
    difficolta: "facile",
    livello: 1,
    famiglia: "figure_ground",
    durata_stimata: 60,
    beneficio: "Allena la percezione visiva e la discriminazione figura-sfondo.",
    config: { game: "figure_ground", stimulusType: "forme" },
  },
  {
    id: "block-design-colori",
    categoria_id: "visuospaziali",
    titolo: "Block Design",
    descrizione: "Copia il pattern di colori toccando le celle.",
    difficolta: "facile",
    livello: 1,
    famiglia: "block_design",
    durata_stimata: 60,
    beneficio: "Allena la costruzione visuospaziale e la memoria visiva.",
    config: { game: "block_design", stimulusType: "colori" },
  },
  {
    id: "pianificazione-tol",
    categoria_id: "esecutive",
    titolo: "Torre di Londra",
    descrizione: "Sposta i dischi per raggiungere la configurazione obiettivo.",
    difficolta: "facile",
    livello: 1,
    famiglia: "pianificazione",
    durata_stimata: 60,
    beneficio: "Allena la pianificazione, la previsione e il problem solving.",
    config: { game: "pianificazione", variant: "tower_of_london" },
  },
  {
    id: "verbal-fluency-categoriale",
    categoria_id: "linguaggio",
    titolo: "Fluenza Verbale",
    descrizione: "Tocca tutte le parole della categoria indicata.",
    difficolta: "facile",
    livello: 1,
    famiglia: "verbal_fluency",
    durata_stimata: 60,
    beneficio: "Allena il recupero lessicale e la fluidità verbale.",
    config: { game: "verbal_fluency", variant: "categoriale" },
  },
  {
    id: "linguaggio-naming",
    categoria_id: "linguaggio",
    titolo: "Naming",
    descrizione: "Guarda l'immagine e scegli il nome giusto tra le opzioni.",
    difficolta: "facile",
    livello: 1,
    famiglia: "linguaggio",
    durata_stimata: 60,
    beneficio: "Allena il recupero dei nomi e il vocabolario attivo.",
    config: { game: "linguaggio", variant: "naming" },
  },
  {
    id: "memoria-prospettica-visiva",
    categoria_id: "memoria",
    titolo: "Memoria Prospettica",
    descrizione: "Classifica le immagini, ma ricorda di reagire al segnale speciale!",
    difficolta: "medio",
    livello: 1,
    famiglia: "memoria_prospettica",
    durata_stimata: 60,
    beneficio: "Allena la memoria prospettica e la gestione dei compiti secondari.",
    config: { game: "memoria_prospettica", cueType: "visivo_saliente" },
  },
  {
    id: "dual-task",
    categoria_id: "attenzione",
    titolo: "Doppio Compito",
    descrizione: "Tappa a ritmo E rispondi alle domande cognitive allo stesso tempo.",
    difficolta: "difficile",
    livello: 1,
    famiglia: "dual_task",
    durata_stimata: 60,
    beneficio: "Allena la divisione dell'attenzione e la gestione di compiti multipli.",
    config: { game: "dual_task" },
  },
  {
    id: "vigilance",
    categoria_id: "attenzione",
    titolo: "Vigilanza",
    descrizione: "Guarda l'orologio e reagisci quando la lancetta fa un salto doppio.",
    difficolta: "medio",
    livello: 1,
    famiglia: "vigilance",
    durata_stimata: 60,
    beneficio: "Allena l'attenzione sostenuta e la vigilanza nel tempo.",
    config: { game: "vigilance" },
  },
  // ── ODD ONE OUT ───────────────────────────────────────────────────────────
  {
    id: "odd-one-out-numeri-lettere",
    categoria_id: "attenzione",
    titolo: "Trova l'Intruso — Cifre e Lettere",
    descrizione: "Trova l'elemento diverso nella griglia di numeri e lettere.",
    difficolta: "facile",
    livello: 1,
    famiglia: "odd_one_out",
    durata_stimata: 60,
    beneficio: "Allena l'attenzione selettiva e la ricerca visiva.",
    config: { game: "odd_one_out", stimulusType: "numeri_lettere" },
  },
  {
    id: "odd-one-out-parole",
    categoria_id: "attenzione",
    titolo: "Trova l'Intruso — Parole",
    descrizione: "Trova la parola che non si ripete nella griglia.",
    difficolta: "medio",
    livello: 1,
    famiglia: "odd_one_out",
    durata_stimata: 60,
    beneficio: "Allena l'attenzione selettiva e il riconoscimento lessicale.",
    config: { game: "odd_one_out", stimulusType: "parole" },
  },
  {
    id: "odd-one-out-forme",
    categoria_id: "attenzione",
    titolo: "Trova l'Intruso — Forme",
    descrizione: "Trova la forma diversa nella griglia.",
    difficolta: "facile",
    livello: 1,
    famiglia: "odd_one_out",
    durata_stimata: 60,
    beneficio: "Allena la percezione visiva e la discriminazione delle forme.",
    config: { game: "odd_one_out", stimulusType: "forme" },
  },

  // ── SORT IT — varianti aggiuntive ─────────────────────────────────────────
  {
    id: "sort-it-forma",
    categoria_id: "esecutive",
    titolo: "Sort It — Forme",
    descrizione: "Smista le carte in categorie in base alla forma. La regola cambia!",
    difficolta: "facile",
    livello: 1,
    famiglia: "sort_it",
    durata_stimata: 60,
    beneficio: "Allena la flessibilità cognitiva e l'inibizione delle risposte automatiche.",
    config: { game: "sort_it", stimulusType: "forma" },
  },
  {
    id: "sort-it-numero",
    categoria_id: "esecutive",
    titolo: "Sort It — Numeri",
    descrizione: "Smista le carte in categorie in base al numero. La regola cambia!",
    difficolta: "medio",
    livello: 1,
    famiglia: "sort_it",
    durata_stimata: 60,
    beneficio: "Allena la flessibilità cognitiva e il ragionamento numerico.",
    config: { game: "sort_it", stimulusType: "numero" },
  },
  {
    id: "sort-it-texture",
    categoria_id: "esecutive",
    titolo: "Sort It — Texture",
    descrizione: "Smista le carte in categorie in base alla texture. La regola cambia!",
    difficolta: "medio",
    livello: 1,
    famiglia: "sort_it",
    durata_stimata: 60,
    beneficio: "Allena la flessibilità cognitiva e la percezione visiva.",
    config: { game: "sort_it", stimulusType: "texture" },
  },
  {
    id: "sort-it-dimensione",
    categoria_id: "esecutive",
    titolo: "Sort It — Dimensione",
    descrizione: "Smista le carte in categorie in base alla dimensione. La regola cambia!",
    difficolta: "difficile",
    livello: 1,
    famiglia: "sort_it",
    durata_stimata: 60,
    beneficio: "Allena la flessibilità cognitiva e la comparazione visiva.",
    config: { game: "sort_it", stimulusType: "dimensione" },
  },


  // ── PASAT LIGHT — variante doppia ─────────────────────────────────────────
  {
    id: "pasat-light-double",
    categoria_id: "attenzione",
    titolo: "PASAT — Cifre Doppie",
    descrizione: "Somma le coppie di numeri a due cifre presentate in sequenza.",
    difficolta: "difficile",
    livello: 1,
    famiglia: "pasat_light",
    durata_stimata: 60,
    beneficio: "Allena la memoria di lavoro aritmetica con numeri più complessi.",
    config: { game: "pasat_light", digitType: "double" },
  },

  // ── UPDATING WM — varianti aggiuntive ─────────────────────────────────────
  {
    id: "updating-wm-parole-living",
    categoria_id: "memoria",
    titolo: "Aggiornamento WM — Esseri Viventi",
    descrizione: "Tieni aggiornato l'ultimo elemento nella sequenza di parole viventi.",
    difficolta: "medio",
    livello: 1,
    famiglia: "updating_wm",
    durata_stimata: 60,
    beneficio: "Allena l'aggiornamento della memoria di lavoro con parole semantiche.",
    config: { game: "updating_wm", stimulusType: "parole_living" },
  },
  {
    id: "updating-wm-parole-non-living",
    categoria_id: "memoria",
    titolo: "Aggiornamento WM — Oggetti",
    descrizione: "Tieni aggiornato l'ultimo elemento nella sequenza di oggetti.",
    difficolta: "medio",
    livello: 1,
    famiglia: "updating_wm",
    durata_stimata: 60,
    beneficio: "Allena l'aggiornamento della memoria di lavoro con oggetti inanimati.",
    config: { game: "updating_wm", stimulusType: "parole_non_living" },
  },
  {
    id: "updating-wm-parole-miste",
    categoria_id: "memoria",
    titolo: "Aggiornamento WM — Parole Miste",
    descrizione: "Tieni aggiornato l'elemento corretto in sequenze di parole miste.",
    difficolta: "difficile",
    livello: 1,
    famiglia: "updating_wm",
    durata_stimata: 60,
    beneficio: "Allena l'aggiornamento della memoria di lavoro con categorie miste.",
    config: { game: "updating_wm", stimulusType: "parole_miste" },
  },
  {
    id: "updating-wm-misti",
    categoria_id: "memoria",
    titolo: "Aggiornamento WM — Stimoli Misti",
    descrizione: "Tieni aggiornato l'elemento corretto alternando numeri e parole.",
    difficolta: "difficile",
    livello: 1,
    famiglia: "updating_wm",
    durata_stimata: 60,
    beneficio: "Allena la memoria di lavoro con switching tra domini.",
    config: { game: "updating_wm", stimulusType: "misti" },
  },

  // ── MEMORIA DI PROSA — varianti aggiuntive ────────────────────────────────
  {
    id: "memoria-prosa-descrittivi",
    categoria_id: "memoria",
    titolo: "Memoria di Prosa — Descrittiva",
    descrizione: "Leggi un testo descrittivo e rispondi alle domande.",
    difficolta: "facile",
    livello: 1,
    famiglia: "memoria_di_prosa",
    durata_stimata: 60,
    beneficio: "Allena la memoria episodica verbale su testi descrittivi.",
    config: { game: "memoria_di_prosa", textType: "descrittivi" },
  },
  {
    id: "memoria-prosa-procedurali",
    categoria_id: "memoria",
    titolo: "Memoria di Prosa — Procedurale",
    descrizione: "Leggi una sequenza di istruzioni e rispondi alle domande.",
    difficolta: "medio",
    livello: 1,
    famiglia: "memoria_di_prosa",
    durata_stimata: 60,
    beneficio: "Allena la memoria episodica verbale su testi procedurali.",
    config: { game: "memoria_di_prosa", textType: "procedurali" },
  },

  // ── MEMORIA LISTA — varianti aggiuntive ───────────────────────────────────
  {
    id: "memoria-lista-parole-semantiche",
    categoria_id: "memoria",
    titolo: "Memoria Lista — Parole per Categoria",
    descrizione: "Memorizza la lista di parole della stessa categoria, poi riconoscile.",
    difficolta: "facile",
    livello: 1,
    famiglia: "memoria_lista",
    durata_stimata: 60,
    beneficio: "Allena la memoria episodica con organizzazione semantica.",
    config: { game: "memoria_lista", stimulusType: "parole_semantiche" },
  },
  {
    id: "memoria-lista-numeri",
    categoria_id: "memoria",
    titolo: "Memoria Lista — Numeri",
    descrizione: "Memorizza la lista di numeri, poi riconoscili tra i distrattori.",
    difficolta: "medio",
    livello: 1,
    famiglia: "memoria_lista",
    durata_stimata: 60,
    beneficio: "Allena la memoria numerica e il riconoscimento sequenziale.",
    config: { game: "memoria_lista", stimulusType: "numeri" },
  },
  {
    id: "memoria-lista-parole-living",
    categoria_id: "memoria",
    titolo: "Memoria Lista — Esseri Viventi",
    descrizione: "Memorizza la lista di esseri viventi, poi riconoscili.",
    difficolta: "facile",
    livello: 1,
    famiglia: "memoria_lista",
    durata_stimata: 60,
    beneficio: "Allena la memoria categoriale per entità animate.",
    config: { game: "memoria_lista", stimulusType: "parole_living" },
  },
  {
    id: "memoria-lista-parole-non-living",
    categoria_id: "memoria",
    titolo: "Memoria Lista — Oggetti",
    descrizione: "Memorizza la lista di oggetti, poi riconoscili tra i distrattori.",
    difficolta: "facile",
    livello: 1,
    famiglia: "memoria_lista",
    durata_stimata: 60,
    beneficio: "Allena la memoria categoriale per oggetti inanimati.",
    config: { game: "memoria_lista", stimulusType: "parole_non_living" },
  },
  {
    id: "memoria-lista-immagini",
    categoria_id: "memoria",
    titolo: "Memoria Lista — Immagini",
    descrizione: "Memorizza le immagini, poi individua quelle già viste.",
    difficolta: "facile",
    livello: 1,
    famiglia: "memoria_lista",
    durata_stimata: 60,
    beneficio: "Allena la memoria visiva e il riconoscimento di immagini.",
    config: { game: "memoria_lista", stimulusType: "immagini" },
  },

  // ── MEMORIA PROSPETTICA — varianti aggiuntive ─────────────────────────────
  {
    id: "memoria-prospettica-semantica",
    categoria_id: "memoria",
    titolo: "Memoria Prospettica — Cue Semantico",
    descrizione: "Classifica le parole, ma ricorda di reagire quando compare la parola speciale!",
    difficolta: "medio",
    livello: 1,
    famiglia: "memoria_prospettica",
    durata_stimata: 60,
    beneficio: "Allena la memoria prospettica con cue semantici meno salienti.",
    config: { game: "memoria_prospettica", cueType: "semantico" },
  },
  {
    id: "memoria-prospettica-time-based",
    categoria_id: "memoria",
    titolo: "Memoria Prospettica — A Tempo",
    descrizione: "Classifica le immagini e ricorda di reagire ogni volta che passa il tempo stabilito.",
    difficolta: "difficile",
    livello: 1,
    famiglia: "memoria_prospettica",
    durata_stimata: 60,
    beneficio: "Allena la memoria prospettica basata sul tempo.",
    config: { game: "memoria_prospettica", cueType: "time_based" },
  },

  // ── GO/NO-GO — varianti aggiuntive ────────────────────────────────────────
  {
    id: "go-nogo-semantico",
    categoria_id: "esecutive",
    titolo: "Go / No-Go — Semantico",
    descrizione: "Tocca gli animali, aspetta per tutto il resto!",
    difficolta: "medio",
    livello: 1,
    famiglia: "go_nogo",
    durata_stimata: 60,
    beneficio: "Allena l'inibizione semantica e l'attenzione selettiva.",
    config: { game: "go_nogo", stimulusType: "semantico" },
  },
  {
    id: "go-nogo-multimodale",
    categoria_id: "esecutive",
    titolo: "Go / No-Go — Multimodale",
    descrizione: "Rispondi solo quando lo stimolo visivo e sonoro corrispondono.",
    difficolta: "difficile",
    livello: 1,
    famiglia: "go_nogo",
    durata_stimata: 60,
    beneficio: "Allena l'inibizione divisa su più canali sensoriali.",
    config: { game: "go_nogo", stimulusType: "multimodale" },
  },
  {
    id: "go-nogo-lessicale",
    categoria_id: "esecutive",
    titolo: "Go / No-Go — Lessicale",
    descrizione: "Tocca le parole reali, ignora le non-parole!",
    difficolta: "medio",
    livello: 1,
    famiglia: "go_nogo",
    durata_stimata: 60,
    beneficio: "Allena l'inibizione lessicale e la decisione rapida sulle parole.",
    config: { game: "go_nogo", stimulusType: "lessicale" },
  },

  // ── PIANIFICAZIONE — variante Brixton ─────────────────────────────────────
  {
    id: "pianificazione-brixton",
    categoria_id: "esecutive",
    titolo: "Brixton — Anticipa il Punto",
    descrizione: "Prevedi la posizione successiva del punto seguendo la regola nascosta.",
    difficolta: "difficile",
    livello: 1,
    famiglia: "pianificazione",
    durata_stimata: 60,
    beneficio: "Allena il ragionamento induttivo e la pianificazione spaziale.",
    config: { game: "pianificazione", variant: "brixton" },
  },

  // ── VERBAL FLUENCY — varianti aggiuntive ──────────────────────────────────
  {
    id: "verbal-fluency-alternata",
    categoria_id: "linguaggio",
    titolo: "Fluenza Verbale — Alternata",
    descrizione: "Alterna parole di due categorie diverse il più velocemente possibile.",
    difficolta: "difficile",
    livello: 1,
    famiglia: "verbal_fluency",
    durata_stimata: 60,
    beneficio: "Allena la flessibilità cognitiva e il recupero lessicale alternato.",
    config: { game: "verbal_fluency", variant: "alternata" },
  },
  {
    id: "verbal-fluency-fonemica",
    categoria_id: "linguaggio",
    titolo: "Fluenza Verbale — Fonemica",
    descrizione: "Tocca tutte le parole che iniziano con la lettera indicata.",
    difficolta: "medio",
    livello: 1,
    famiglia: "verbal_fluency",
    durata_stimata: 60,
    beneficio: "Allena la fluenza fonemica e il recupero lessicale fonologico.",
    config: { game: "verbal_fluency", variant: "fonemica" },
  },

  // ── LINGUAGGIO — varianti aggiuntive ──────────────────────────────────────
  {
    id: "linguaggio-lexical-decision",
    categoria_id: "linguaggio",
    titolo: "Decisione Lessicale",
    descrizione: "Decidi rapidamente se la stringa è una parola reale o inventata.",
    difficolta: "medio",
    livello: 1,
    famiglia: "linguaggio",
    durata_stimata: 60,
    beneficio: "Allena il riconoscimento lessicale e la velocità di elaborazione.",
    config: { game: "linguaggio", variant: "lexical_decision" },
  },
  {
    id: "linguaggio-sentence-anagram",
    categoria_id: "linguaggio",
    titolo: "Anagramma di Frase",
    descrizione: "Riordina le parole mescolate per formare una frase corretta.",
    difficolta: "medio",
    livello: 1,
    famiglia: "linguaggio",
    durata_stimata: 60,
    beneficio: "Allena la comprensione sintattica e la memoria di lavoro verbale.",
    config: { game: "linguaggio", variant: "sentence_anagram" },
  },
  {
    id: "linguaggio-semantic-relatedness",
    categoria_id: "linguaggio",
    titolo: "Relazione Semantica",
    descrizione: "Decidi se le due parole sono semanticamente correlate.",
    difficolta: "facile",
    livello: 1,
    famiglia: "linguaggio",
    durata_stimata: 60,
    beneficio: "Allena la memoria semantica e l'associazione concettuale.",
    config: { game: "linguaggio", variant: "semantic_relatedness" },
  },
  {
    id: "linguaggio-proverb-completion",
    categoria_id: "linguaggio",
    titolo: "Proverbi",
    descrizione: "Completa i proverbi italiani scegliendo la parola giusta.",
    difficolta: "facile",
    livello: 1,
    famiglia: "linguaggio",
    durata_stimata: 60,
    beneficio: "Allena la memoria culturale semantica e la conoscenza idiomatica.",
    config: { game: "linguaggio", variant: "proverb_completion" },
  },

  // ── MENTAL ROTATION — variante oggetti 3D ─────────────────────────────────
  {
    id: "mental-rotation-oggetti-3d",
    categoria_id: "visuospaziali",
    titolo: "Rotazione Mentale — Oggetti 3D",
    descrizione: "Le due figure tridimensionali sono uguali o specchiate?",
    difficolta: "difficile",
    livello: 1,
    famiglia: "mental_rotation",
    durata_stimata: 60,
    beneficio: "Allena la rotazione mentale su oggetti tridimensionali complessi.",
    config: { game: "mental_rotation", stimulusType: "oggetti_3d" },
  },

  // ── FIGURE GROUND — variante oggetti ──────────────────────────────────────
  {
    id: "figure-ground-oggetti",
    categoria_id: "visuospaziali",
    titolo: "Figura e Sfondo — Oggetti",
    descrizione: "Trova l'oggetto nascosto nella scena complessa.",
    difficolta: "medio",
    livello: 1,
    famiglia: "figure_ground",
    durata_stimata: 60,
    beneficio: "Allena la percezione figura-sfondo su scene realistiche.",
    config: { game: "figure_ground", stimulusType: "oggetti" },
  },

  // ── BLOCK DESIGN — variante bianco/nero ───────────────────────────────────
  {
    id: "block-design-bw",
    categoria_id: "visuospaziali",
    titolo: "Block Design — Bianco e Nero",
    descrizione: "Copia il pattern in bianco e nero toccando le celle.",
    difficolta: "medio",
    livello: 1,
    famiglia: "block_design",
    durata_stimata: 60,
    beneficio: "Allena la costruzione visuospaziale senza l'aiuto del colore.",
    config: { game: "block_design", stimulusType: "bw" },
  },
];

export const mockEsercizioDelGiorno = mockEsercizi[2]; // "anagramma" — primo non completato oggi

type EserciziDelGiornoItem = {
  id: string;
  titolo: string;
  categoria_id: string;
  livello: number;
  durata_stimata: number;
  completato: boolean;
  risultato: { tempo_secondi: number; accuratezza: number } | null;
};

// TODO: da Supabase — SELECT * FROM esercizi_del_giorno WHERE data = TODAY() JOIN sessioni
export const mockEserciziDelGiornoList: EserciziDelGiornoItem[] = [
  {
    id: "sequence-tap-immagini",
    titolo: "Sequenza di Immagini",
    categoria_id: "memoria",
    livello: 1,
    durata_stimata: 60,
    completato: false,
    risultato: null,
  },
  {
    id: "pasat-light-single",
    titolo: "PASAT — Cifre",
    categoria_id: "attenzione",
    livello: 1,
    durata_stimata: 60,
    completato: false,
    risultato: null,
  },
  {
    id: "linguaggio-semantic-relatedness",
    titolo: "Relazione Semantica",
    categoria_id: "linguaggio",
    livello: 1,
    durata_stimata: 60,
    completato: false,
    risultato: null,
  },
  {
    id: "dccs-light",
    titolo: "DCCS — Classifica Carte",
    categoria_id: "esecutive",
    livello: 1,
    durata_stimata: 60,
    completato: false,
    risultato: null,
  },
  {
    id: "block-design-colori",
    titolo: "Block Design",
    categoria_id: "visuospaziali",
    livello: 1,
    durata_stimata: 60,
    completato: false,
    risultato: null,
  },
];

// TODO: in futuro questo verrà da Supabase (sessioni di oggi)
// TODO: sostituire con query Supabase — SELECT count(*) FROM sessioni WHERE utente_id = ? AND data = TODAY()
// La logica di blocco è: se sessioni_oggi >= LIMITE_ESERCIZI_GIORNO (5) → mostra modale pausa attiva
export const mockEserciziOggi = mockEserciziDelGiornoList.filter((e) => e.completato).length;

// ─── Mock Medaglie ────────────────────────────────────────────────────────────
// Ogni medaglia si ottiene completando 5 esercizi al giorno per X giorni consecutivi.
// guadagnata_at: valorizzato solo per le medaglie già sbloccate (streak mock = 7)
export const mockMedaglie = [
  { id: "giorno-1",   nome: "Primo giorno",     giorni: 1,   guadagnata_at: "2026-04-13" },
  { id: "giorni-2",   nome: "2 giorni consecutivi",   giorni: 2,   guadagnata_at: "2026-04-14" },
  { id: "giorni-3",   nome: "3 giorni consecutivi",   giorni: 3,   guadagnata_at: "2026-04-15" },
  { id: "giorni-7",   nome: "7 giorni consecutivi",   giorni: 7,   guadagnata_at: "2026-04-19" },
  { id: "giorni-10",  nome: "10 giorni consecutivi",  giorni: 10 },
  { id: "giorni-14",  nome: "14 giorni consecutivi",  giorni: 14 },
  { id: "giorni-28",  nome: "28 giorni consecutivi",  giorni: 28 },
  { id: "giorni-50",  nome: "50 giorni consecutivi",  giorni: 50 },
  { id: "giorni-100", nome: "100 giorni consecutivi", giorni: 100 },
  { id: "giorni-200", nome: "200 giorni consecutivi", giorni: 200 },
  { id: "giorni-365", nome: "365 giorni consecutivi", giorni: 365 },
];

// ─── Mock Progressi ───────────────────────────────────────────────────────────
// TODO: aggiungere dati reali per tipo4/tipo5 quando i nomi sono definiti
export const mockProgressiSettimanali = [
  { giorno: "Lun", esercizi: 3, memoria: 1, attenzione: 1, linguaggio: 0, esecutive: 1, visuospaziali: 0 },
  { giorno: "Mar", esercizi: 2, memoria: 0, attenzione: 0, linguaggio: 1, esecutive: 0, visuospaziali: 1 },
  { giorno: "Mer", esercizi: 0, memoria: 0, attenzione: 0, linguaggio: 0, esecutive: 0, visuospaziali: 0 },
  { giorno: "Gio", esercizi: 0, memoria: 0, attenzione: 0, linguaggio: 0, esecutive: 0, visuospaziali: 0 },
  { giorno: "Ven", esercizi: 4, memoria: 1, attenzione: 0, linguaggio: 1, esecutive: 1, visuospaziali: 1 },
  { giorno: "Sab", esercizi: 2, memoria: 1, attenzione: 0, linguaggio: 0, esecutive: 0, visuospaziali: 1 },
  { giorno: "Dom", esercizi: 2, memoria: 0, attenzione: 0, linguaggio: 1, esecutive: 1, visuospaziali: 0 },
];

export const mockScoreCategorie = [
  {
    categoria: "Memoria", icona: "brain", colore: "#2563EB", score: 74,
    trend: "crescita" as const, livello: 3, sessioni: 8,
    descrizione: "La tua memoria è al 74%",
    storico: [
      { label: "6 Mar",  score: 52 }, { label: "10 Mar", score: 56 },
      { label: "14 Mar", score: 59 }, { label: "18 Mar", score: 62 },
      { label: "22 Mar", score: 64 }, { label: "25 Mar", score: 67 },
      { label: "27 Mar", score: 68 }, { label: "29 Mar", score: 70 },
      { label: "31 Mar", score: 71 }, { label: "1 Apr",  score: 72 },
      { label: "2 Apr",  score: 73 }, { label: "3 Apr",  score: 74 },
    ],
    // TODO: sostituire con query Supabase — SELECT data, livello FROM sessioni WHERE categoria = 'memoria' ORDER BY data
    storicoLivello: [
      { label: "6 Mar",  livello: 1 }, { label: "10 Mar", livello: 1 },
      { label: "14 Mar", livello: 1 }, { label: "18 Mar", livello: 2 },
      { label: "22 Mar", livello: 2 }, { label: "25 Mar", livello: 2 },
      { label: "27 Mar", livello: 2 }, { label: "29 Mar", livello: 2 },
      { label: "31 Mar", livello: 3 }, { label: "1 Apr",  livello: 3 },
      { label: "2 Apr",  livello: 3 }, { label: "3 Apr",  livello: 3 },
      { label: "6 Apr",  livello: 3 }, { label: "7 Apr",  livello: 3 },
      { label: "8 Apr",  livello: 3 }, { label: "9 Apr",  livello: 4 },
      { label: "10 Apr", livello: 4 },
    ],
  },
  {
    categoria: "Attenzione", icona: "target", colore: "#7C3AED", score: 61,
    trend: "stabile" as const, livello: 2, sessioni: 5,
    descrizione: "La tua attenzione è al 61%",
    storico: [
      { label: "6 Mar",  score: 58 }, { label: "10 Mar", score: 62 },
      { label: "14 Mar", score: 59 }, { label: "18 Mar", score: 63 },
      { label: "22 Mar", score: 60 }, { label: "25 Mar", score: 64 },
      { label: "27 Mar", score: 59 }, { label: "29 Mar", score: 63 },
      { label: "31 Mar", score: 60 }, { label: "1 Apr",  score: 62 },
      { label: "2 Apr",  score: 60 }, { label: "3 Apr",  score: 61 },
    ],
    // TODO: sostituire con query Supabase — SELECT data, livello FROM sessioni WHERE categoria = 'attenzione' ORDER BY data
    storicoLivello: [
      { label: "6 Mar",  livello: 2 }, { label: "10 Mar", livello: 2 },
      { label: "14 Mar", livello: 2 }, { label: "18 Mar", livello: 2 },
      { label: "22 Mar", livello: 2 }, { label: "25 Mar", livello: 2 },
      { label: "27 Mar", livello: 2 }, { label: "29 Mar", livello: 2 },
      { label: "31 Mar", livello: 2 }, { label: "1 Apr",  livello: 2 },
      { label: "2 Apr",  livello: 2 }, { label: "3 Apr",  livello: 2 },
      { label: "6 Apr",  livello: 2 }, { label: "7 Apr",  livello: 2 },
      { label: "8 Apr",  livello: 3 }, { label: "9 Apr",  livello: 3 },
      { label: "10 Apr", livello: 3 },
    ],
  },
  {
    categoria: "Linguaggio", icona: "chat", colore: "#16A34A", score: 88,
    trend: "calo" as const, livello: 4, sessioni: 6,
    descrizione: "Il tuo linguaggio è all'88%",
    storico: [
      { label: "6 Mar",  score: 96 }, { label: "10 Mar", score: 94 },
      { label: "14 Mar", score: 95 }, { label: "18 Mar", score: 93 },
      { label: "22 Mar", score: 92 }, { label: "25 Mar", score: 91 },
      { label: "27 Mar", score: 92 }, { label: "29 Mar", score: 90 },
      { label: "31 Mar", score: 90 }, { label: "1 Apr",  score: 89 },
      { label: "2 Apr",  score: 89 }, { label: "3 Apr",  score: 88 },
    ],
    // TODO: sostituire con query Supabase — SELECT data, livello FROM sessioni WHERE categoria = 'linguaggio' ORDER BY data
    storicoLivello: [
      { label: "6 Mar",  livello: 5 }, { label: "10 Mar", livello: 5 },
      { label: "14 Mar", livello: 5 }, { label: "18 Mar", livello: 5 },
      { label: "22 Mar", livello: 4 }, { label: "25 Mar", livello: 4 },
      { label: "27 Mar", livello: 4 }, { label: "29 Mar", livello: 4 },
      { label: "31 Mar", livello: 4 }, { label: "1 Apr",  livello: 4 },
      { label: "2 Apr",  livello: 4 }, { label: "3 Apr",  livello: 4 },
      { label: "6 Apr",  livello: 4 }, { label: "7 Apr",  livello: 4 },
      { label: "8 Apr",  livello: 4 }, { label: "9 Apr",  livello: 5 },
      { label: "10 Apr", livello: 5 },
    ],
  },
  {
    categoria: "Esecutive", icona: "puzzle", colore: "#D97706", score: 68,
    trend: "crescita" as const, livello: 2, sessioni: 7,
    descrizione: "Le tue funzioni esecutive sono al 68%",
    storico: [
      { label: "6 Mar",  score: 48 }, { label: "10 Mar", score: 52 },
      { label: "14 Mar", score: 54 }, { label: "18 Mar", score: 57 },
      { label: "22 Mar", score: 59 }, { label: "25 Mar", score: 61 },
      { label: "27 Mar", score: 62 }, { label: "29 Mar", score: 63 },
      { label: "31 Mar", score: 64 }, { label: "1 Apr",  score: 65 },
      { label: "2 Apr",  score: 66 }, { label: "3 Apr",  score: 68 },
    ],
    storicoLivello: [
      { label: "6 Mar",  livello: 1 }, { label: "14 Mar", livello: 1 },
      { label: "22 Mar", livello: 1 }, { label: "29 Mar", livello: 1 },
      { label: "31 Mar", livello: 2 }, { label: "1 Apr",  livello: 2 },
      { label: "2 Apr",  livello: 2 }, { label: "3 Apr",  livello: 2 },
      { label: "6 Apr",  livello: 2 }, { label: "7 Apr",  livello: 2 },
      { label: "8 Apr",  livello: 2 }, { label: "9 Apr",  livello: 3 },
      { label: "10 Apr", livello: 3 },
    ],
  },
  {
    categoria: "Visuospaziali", icona: "eye", colore: "#0F766E", score: 57,
    trend: "stabile" as const, livello: 1, sessioni: 6,
    descrizione: "Le tue abilità visuospaziali sono al 57%",
    storico: [
      { label: "6 Mar",  score: 54 }, { label: "10 Mar", score: 56 },
      { label: "14 Mar", score: 55 }, { label: "18 Mar", score: 58 },
      { label: "22 Mar", score: 56 }, { label: "25 Mar", score: 57 },
      { label: "27 Mar", score: 58 }, { label: "29 Mar", score: 57 },
      { label: "31 Mar", score: 56 }, { label: "1 Apr",  score: 57 },
      { label: "2 Apr",  score: 58 }, { label: "3 Apr",  score: 57 },
    ],
    storicoLivello: [
      { label: "6 Mar",  livello: 1 }, { label: "14 Mar", livello: 1 },
      { label: "22 Mar", livello: 1 }, { label: "29 Mar", livello: 1 },
      { label: "31 Mar", livello: 1 }, { label: "1 Apr",  livello: 1 },
      { label: "2 Apr",  livello: 1 }, { label: "3 Apr",  livello: 1 },
      { label: "6 Apr",  livello: 1 }, { label: "7 Apr",  livello: 1 },
      { label: "8 Apr",  livello: 1 }, { label: "9 Apr",  livello: 1 },
      { label: "10 Apr", livello: 1 },
    ],
  },
];

export const mockSessioniRecenti = [
  { titolo: "Ricorda le Parole",  categoria: "Memoria",       score: 80,  data: "Ieri",        icona: "brain",  trend: "crescita" as const },
  { titolo: "Test Stroop",        categoria: "Attenzione",    score: 70,  data: "Ieri",         icona: "target", trend: "stabile"  as const },
  { titolo: "Anagramma",          categoria: "Linguaggio",    score: 100, data: "Ieri",         icona: "chat",   trend: "calo"     as const },
  { titolo: "Torre di Hanoi",     categoria: "Esecutive",     score: 72,  data: "Ieri",         icona: "puzzle", trend: "crescita" as const },
  { titolo: "Rotazione Mentale",  categoria: "Visuospaziali", score: 58,  data: "2 giorni fa",  icona: "eye",    trend: "stabile"  as const },
  { titolo: "Sequenza di Colori", categoria: "Memoria",       score: 60,  data: "2 giorni fa",  icona: "brain",  trend: "stabile"  as const },
];

// ─── Mock Messaggi Famigliari ─────────────────────────────────────────────────
// TODO: sostituire con dati reali da Supabase (tabella messaggi_familiari)
export const mockMessaggiFamiliari = [
  { id: "1", mittente: "Marco", relazione: "Figlio",  data: "8 Apr 2026",  testo: "Ciao mamma! Brava, continua così! Sono così orgoglioso di te.", letto: false },
  { id: "2", mittente: "Marco", relazione: "Figlio",  data: "6 Apr 2026",  testo: "Ricordati di fare l'esercizio oggi! Ti voglio bene.", letto: true },
  { id: "3", mittente: "Sara",  relazione: "Figlia",  data: "4 Apr 2026",  testo: "Mamma hai fatto 3 giorni di fila! 🎉 Bravissima!", letto: true },
  { id: "4", mittente: "Marco", relazione: "Figlio",  data: "2 Apr 2026",  testo: "Come stai oggi? Hai fatto l'esercizio di oggi?", letto: true },
  { id: "5", mittente: "Luca",  relazione: "Nipote",  data: "31 Mar 2026", testo: "Nonna sei fortissima! Vai avanti così 🌟", letto: true },
];

// ─── Mock Storico Giornaliero ─────────────────────────────────────────────────
export const mockTotaleSettimanaScorsa = 7;

// TODO: sostituire con dati reali da Supabase (tabella sessioni)
// Struttura: { data: string (YYYY-MM-DD), sessioni: SessioneStorico[] }
// SessioneStorico: { nome_esercizio, categoria, icona, livello, score }
const S5 = [
  { nome_esercizio: "Ricorda le parole",   categoria: "Memoria",    icona: "brain",  livello: 3, score: 78 },
  { nome_esercizio: "Trova le differenze", categoria: "Attenzione", icona: "target", livello: 2, score: 65 },
  { nome_esercizio: "Anagramma",           categoria: "Linguaggio", icona: "chat",   livello: 1, score: 84 },
  { nome_esercizio: "Torre di Hanoi",      categoria: "Esecutive",  icona: "puzzle", livello: 2, score: 72 },
  { nome_esercizio: "Rotazione Mentale",   categoria: "Visuospaziali", icona: "eye", livello: 2, score: 69 },
];

export const mockStoricoGiornaliero = [
  { data: "2026-04-15", sessioni: S5 },
  { data: "2026-04-14", sessioni: S5 },
  { data: "2026-04-13", sessioni: S5 },
  { data: "2026-04-12", sessioni: S5 },
  { data: "2026-04-11", sessioni: S5 },
  { data: "2026-04-10", sessioni: S5 },
  {
    data: "2026-04-09",
    sessioni: [
      { nome_esercizio: "Ricorda le parole",   categoria: "Memoria",    icona: "brain",  livello: 3, score: 78 },
      { nome_esercizio: "Trova le differenze", categoria: "Attenzione", icona: "target", livello: 2, score: 65 },
    ],
  },
  {
    data: "2026-04-08",
    sessioni: S5,
  },
  {
    data: "2026-04-07",
    sessioni: S5,
  },
  {
    data: "2026-04-06",
    sessioni: [
      { nome_esercizio: "Ricorda le parole",   categoria: "Memoria",    icona: "brain",  livello: 3, score: 74 },
      { nome_esercizio: "Completa la frase",   categoria: "Linguaggio", icona: "chat",   livello: 4, score: 86 },
    ],
  },
  {
    data: "2026-04-03",
    sessioni: S5,
  },
  {
    data: "2026-04-02",
    sessioni: [],
  },
  {
    data: "2026-04-01",
    sessioni: S5,
  },
  {
    data: "2026-03-31",
    sessioni: S5,
  },
  {
    data: "2026-03-30",
    sessioni: [
      { nome_esercizio: "Memoria visiva",      categoria: "Memoria",    icona: "brain",  livello: 3, score: 68 },
      { nome_esercizio: "Trova l'intruso",     categoria: "Attenzione", icona: "target", livello: 2, score: 58 },
    ],
  },
];
