/**
 * components/esercizi/families/word-chain/words.ts
 *
 * Pool lessicale per Word Chain Alfabetico.
 * ~380 parole italiane concrete distribuite su tutte e 21 lettere dell'alfabeto italiano.
 * Ogni parola ha categoria semantica per vincolo distanza (alta/media).
 *
 * Categorie: animali, frutta, verdure, cibi, oggetti, mestieri, natura, veicoli, luoghi
 */

export interface WCWord {
  parola:    string;
  categoria: string;
}

// Alfabeto italiano (21 lettere — J K W X Y omesse o ridotte)
export const ITALIAN_ALPHABET = [
  "A","B","C","D","E","F","G","H","I","L",
  "M","N","O","P","Q","R","S","T","U","V","Z",
] as const;

export type LetteraIT = typeof ITALIAN_ALPHABET[number];

export const PAROLE_PER_LETTERA: Record<LetteraIT, WCWord[]> = {
  A: [
    { parola: "Aquila",      categoria: "animali"  },
    { parola: "Asino",       categoria: "animali"  },
    { parola: "Ape",         categoria: "animali"  },
    { parola: "Anguilla",    categoria: "animali"  },
    { parola: "Ananas",      categoria: "frutta"   },
    { parola: "Arancia",     categoria: "frutta"   },
    { parola: "Albicocca",   categoria: "frutta"   },
    { parola: "Avocado",     categoria: "frutta"   },
    { parola: "Aglio",       categoria: "verdure"  },
    { parola: "Asparago",    categoria: "verdure"  },
    { parola: "Armadio",     categoria: "oggetti"  },
    { parola: "Ancora",      categoria: "oggetti"  },
    { parola: "Arco",        categoria: "oggetti"  },
    { parola: "Avvocato",    categoria: "mestieri" },
    { parola: "Astronauta",  categoria: "mestieri" },
    { parola: "Architetto",  categoria: "mestieri" },
    { parola: "Abete",       categoria: "natura"   },
    { parola: "Alloro",      categoria: "natura"   },
    { parola: "Aereo",       categoria: "veicoli"  },
    { parola: "Autobus",     categoria: "veicoli"  },
    { parola: "Ambulanza",   categoria: "veicoli"  },
    { parola: "Aeroporto",   categoria: "luoghi"   },
    { parola: "Albergo",     categoria: "luoghi"   },
  ],
  B: [
    { parola: "Balena",         categoria: "animali"  },
    { parola: "Bisonte",        categoria: "animali"  },
    { parola: "Bufalo",         categoria: "animali"  },
    { parola: "Bue",            categoria: "animali"  },
    { parola: "Banana",         categoria: "frutta"   },
    { parola: "Burro",          categoria: "cibi"     },
    { parola: "Biscotto",       categoria: "cibi"     },
    { parola: "Bistecca",       categoria: "cibi"     },
    { parola: "Basilico",       categoria: "cibi"     },
    { parola: "Borsa",          categoria: "oggetti"  },
    { parola: "Bottiglia",      categoria: "oggetti"  },
    { parola: "Baule",          categoria: "oggetti"  },
    { parola: "Barbiere",       categoria: "mestieri" },
    { parola: "Biologo",        categoria: "mestieri" },
    { parola: "Bibliotecario",  categoria: "mestieri" },
    { parola: "Bambù",          categoria: "natura"   },
    { parola: "Betulla",        categoria: "natura"   },
    { parola: "Bosco",          categoria: "natura"   },
    { parola: "Barca",          categoria: "veicoli"  },
    { parola: "Biblioteca",     categoria: "luoghi"   },
  ],
  C: [
    { parola: "Cavallo",     categoria: "animali"  },
    { parola: "Cane",        categoria: "animali"  },
    { parola: "Coccodrillo", categoria: "animali"  },
    { parola: "Capra",       categoria: "animali"  },
    { parola: "Cervo",       categoria: "animali"  },
    { parola: "Cicogna",     categoria: "animali"  },
    { parola: "Ciliegia",    categoria: "frutta"   },
    { parola: "Cocomero",    categoria: "frutta"   },
    { parola: "Carota",      categoria: "verdure"  },
    { parola: "Cavolo",      categoria: "verdure"  },
    { parola: "Coltello",    categoria: "oggetti"  },
    { parola: "Cappello",    categoria: "oggetti"  },
    { parola: "Calzino",     categoria: "oggetti"  },
    { parola: "Cuoco",       categoria: "mestieri" },
    { parola: "Chirurgo",    categoria: "mestieri" },
    { parola: "Carpentiere", categoria: "mestieri" },
    { parola: "Ciliegio",    categoria: "natura"   },
    { parola: "Cipresso",    categoria: "natura"   },
    { parola: "Camion",      categoria: "veicoli"  },
    { parola: "Chiesa",      categoria: "luoghi"   },
    { parola: "Castello",    categoria: "luoghi"   },
  ],
  D: [
    { parola: "Delfino",    categoria: "animali"  },
    { parola: "Daino",      categoria: "animali"  },
    { parola: "Donnola",    categoria: "animali"  },
    { parola: "Dattero",    categoria: "frutta"   },
    { parola: "Divano",     categoria: "oggetti"  },
    { parola: "Dizionario", categoria: "oggetti"  },
    { parola: "Diploma",    categoria: "oggetti"  },
    { parola: "Disco",      categoria: "oggetti"  },
    { parola: "Dado",       categoria: "cibi"     },
    { parola: "Dottore",    categoria: "mestieri" },
    { parola: "Dentista",   categoria: "mestieri" },
    { parola: "Direttore",  categoria: "mestieri" },
    { parola: "Detective",  categoria: "mestieri" },
    { parola: "Designer",   categoria: "mestieri" },
    { parola: "Duna",       categoria: "natura"   },
    { parola: "Delta",      categoria: "natura"   },
    { parola: "Duomo",      categoria: "luoghi"   },
    { parola: "Deposito",   categoria: "luoghi"   },
    { parola: "Dogana",     categoria: "luoghi"   },
  ],
  E: [
    { parola: "Elefante",      categoria: "animali"  },
    { parola: "Ermellino",     categoria: "animali"  },
    { parola: "Elmo",          categoria: "oggetti"  },
    { parola: "Elastico",      categoria: "oggetti"  },
    { parola: "Elmetto",       categoria: "oggetti"  },
    { parola: "Enciclopedia",  categoria: "oggetti"  },
    { parola: "Esca",          categoria: "oggetti"  },
    { parola: "Espresso",      categoria: "cibi"     },
    { parola: "Erba",          categoria: "natura"   },
    { parola: "Eucalipto",     categoria: "natura"   },
    { parola: "Erica",         categoria: "natura"   },
    { parola: "Elettricista",  categoria: "mestieri" },
    { parola: "Editore",       categoria: "mestieri" },
    { parola: "Economista",    categoria: "mestieri" },
    { parola: "Esploratore",   categoria: "mestieri" },
    { parola: "Edificio",      categoria: "luoghi"   },
    { parola: "Eremo",         categoria: "luoghi"   },
    { parola: "Enoteca",       categoria: "luoghi"   },
  ],
  F: [
    { parola: "Falco",       categoria: "animali"  },
    { parola: "Farfalla",    categoria: "animali"  },
    { parola: "Foca",        categoria: "animali"  },
    { parola: "Formica",     categoria: "animali"  },
    { parola: "Fagiano",     categoria: "animali"  },
    { parola: "Fico",        categoria: "frutta"   },
    { parola: "Fragola",     categoria: "frutta"   },
    { parola: "Fagiolo",     categoria: "verdure"  },
    { parola: "Finocchio",   categoria: "verdure"  },
    { parola: "Formaggio",   categoria: "cibi"     },
    { parola: "Farina",      categoria: "cibi"     },
    { parola: "Forbici",     categoria: "oggetti"  },
    { parola: "Forchetta",   categoria: "oggetti"  },
    { parola: "Filo",        categoria: "oggetti"  },
    { parola: "Falegname",   categoria: "mestieri" },
    { parola: "Farmacista",  categoria: "mestieri" },
    { parola: "Fotografo",   categoria: "mestieri" },
    { parola: "Faggio",      categoria: "natura"   },
    { parola: "Felce",       categoria: "natura"   },
    { parola: "Foresta",     categoria: "natura"   },
    { parola: "Fortezza",    categoria: "luoghi"   },
    { parola: "Furgone",     categoria: "veicoli"  },
  ],
  G: [
    { parola: "Gatto",       categoria: "animali"  },
    { parola: "Giraffa",     categoria: "animali"  },
    { parola: "Gorilla",     categoria: "animali"  },
    { parola: "Gallo",       categoria: "animali"  },
    { parola: "Gufo",        categoria: "animali"  },
    { parola: "Gabbiano",    categoria: "animali"  },
    { parola: "Grissino",    categoria: "cibi"     },
    { parola: "Gorgonzola",  categoria: "cibi"     },
    { parola: "Guanto",      categoria: "oggetti"  },
    { parola: "Giornale",    categoria: "oggetti"  },
    { parola: "Giacca",      categoria: "oggetti"  },
    { parola: "Gomma",       categoria: "oggetti"  },
    { parola: "Geometra",    categoria: "mestieri" },
    { parola: "Giudice",     categoria: "mestieri" },
    { parola: "Giardiniere", categoria: "mestieri" },
    { parola: "Ginepro",     categoria: "natura"   },
    { parola: "Giglio",      categoria: "natura"   },
    { parola: "Giardino",    categoria: "luoghi"   },
    { parola: "Golfo",       categoria: "luoghi"   },
  ],
  H: [
    { parola: "Hamster",    categoria: "animali"  },
    { parola: "Halibut",    categoria: "animali"  },
    { parola: "Hamburger",  categoria: "cibi"     },
    { parola: "Humus",      categoria: "cibi"     },
    { parola: "Hockey",     categoria: "oggetti"  },
    { parola: "Hobby",      categoria: "oggetti"  },
    { parola: "Hotel",      categoria: "luoghi"   },
    { parola: "Hall",       categoria: "luoghi"   },
    { parola: "Habitat",    categoria: "luoghi"   },
    { parola: "Hovercraft", categoria: "veicoli"  },
  ],
  I: [
    { parola: "Iguana",        categoria: "animali"  },
    { parola: "Ibis",          categoria: "animali"  },
    { parola: "Iena",          categoria: "animali"  },
    { parola: "Ippopotamo",    categoria: "animali"  },
    { parola: "Insalata",      categoria: "verdure"  },
    { parola: "Impermeabile",  categoria: "oggetti"  },
    { parola: "Interruttore",  categoria: "oggetti"  },
    { parola: "Inchiostro",    categoria: "oggetti"  },
    { parola: "Ingegnere",     categoria: "mestieri" },
    { parola: "Insegnante",    categoria: "mestieri" },
    { parola: "Infermiere",    categoria: "mestieri" },
    { parola: "Idraulico",     categoria: "mestieri" },
    { parola: "Investigatore", categoria: "mestieri" },
    { parola: "Inventore",     categoria: "mestieri" },
    { parola: "Idrovolante",   categoria: "veicoli"  },
    { parola: "Isola",         categoria: "luoghi"   },
    { parola: "Istituto",      categoria: "luoghi"   },
  ],
  L: [
    { parola: "Leone",       categoria: "animali"  },
    { parola: "Lepre",       categoria: "animali"  },
    { parola: "Lince",       categoria: "animali"  },
    { parola: "Lupo",        categoria: "animali"  },
    { parola: "Lucertola",   categoria: "animali"  },
    { parola: "Leopardo",    categoria: "animali"  },
    { parola: "Limone",      categoria: "frutta"   },
    { parola: "Lampone",     categoria: "frutta"   },
    { parola: "Lampada",     categoria: "oggetti"  },
    { parola: "Letto",       categoria: "oggetti"  },
    { parola: "Libro",       categoria: "oggetti"  },
    { parola: "Lavatrice",   categoria: "oggetti"  },
    { parola: "Lana",        categoria: "oggetti"  },
    { parola: "Lucchetto",   categoria: "oggetti"  },
    { parola: "Libraio",     categoria: "mestieri" },
    { parola: "Logopedista", categoria: "mestieri" },
    { parola: "Lauro",       categoria: "natura"   },
    { parola: "Lavanda",     categoria: "natura"   },
    { parola: "Lago",        categoria: "luoghi"   },
    { parola: "Litorale",    categoria: "luoghi"   },
  ],
  M: [
    { parola: "Mucca",     categoria: "animali"  },
    { parola: "Maiale",    categoria: "animali"  },
    { parola: "Marmotta",  categoria: "animali"  },
    { parola: "Medusa",    categoria: "animali"  },
    { parola: "Merluzzo",  categoria: "animali"  },
    { parola: "Mela",      categoria: "frutta"   },
    { parola: "Melone",    categoria: "frutta"   },
    { parola: "Mandorla",  categoria: "frutta"   },
    { parola: "Mandarino", categoria: "frutta"   },
    { parola: "Mora",      categoria: "frutta"   },
    { parola: "Martello",  categoria: "oggetti"  },
    { parola: "Matita",    categoria: "oggetti"  },
    { parola: "Microfono", categoria: "oggetti"  },
    { parola: "Medico",    categoria: "mestieri" },
    { parola: "Meccanico", categoria: "mestieri" },
    { parola: "Muratore",  categoria: "mestieri" },
    { parola: "Magnolia",  categoria: "natura"   },
    { parola: "Mimosa",    categoria: "natura"   },
    { parola: "Montagna",  categoria: "luoghi"   },
    { parola: "Museo",     categoria: "luoghi"   },
  ],
  N: [
    { parola: "Nutria",        categoria: "animali"  },
    { parola: "Nibbio",        categoria: "animali"  },
    { parola: "Nocciola",      categoria: "frutta"   },
    { parola: "Noce",          categoria: "frutta"   },
    { parola: "Nespola",       categoria: "frutta"   },
    { parola: "Nastro",        categoria: "oggetti"  },
    { parola: "Numero",        categoria: "oggetti"  },
    { parola: "Nido",          categoria: "natura"   },
    { parola: "Narciso",       categoria: "natura"   },
    { parola: "Nocciolo",      categoria: "natura"   },
    { parola: "Nebbia",        categoria: "natura"   },
    { parola: "Nuvola",        categoria: "natura"   },
    { parola: "Notaio",        categoria: "mestieri" },
    { parola: "Nutrizionista", categoria: "mestieri" },
    { parola: "Navigatore",    categoria: "mestieri" },
    { parola: "Nave",          categoria: "veicoli"  },
    { parola: "Negozio",       categoria: "luoghi"   },
  ],
  O: [
    { parola: "Orso",       categoria: "animali"  },
    { parola: "Orca",       categoria: "animali"  },
    { parola: "Orango",     categoria: "animali"  },
    { parola: "Ostrica",    categoria: "animali"  },
    { parola: "Oca",        categoria: "animali"  },
    { parola: "Oliva",      categoria: "frutta"   },
    { parola: "Origano",    categoria: "cibi"     },
    { parola: "Olio",       categoria: "cibi"     },
    { parola: "Ombrello",   categoria: "oggetti"  },
    { parola: "Orologio",   categoria: "oggetti"  },
    { parola: "Occhiali",   categoria: "oggetti"  },
    { parola: "Oculista",   categoria: "mestieri" },
    { parola: "Ortopedico", categoria: "mestieri" },
    { parola: "Operaio",    categoria: "mestieri" },
    { parola: "Orafo",      categoria: "mestieri" },
    { parola: "Olmo",       categoria: "natura"   },
    { parola: "Oleandro",   categoria: "natura"   },
    { parola: "Orchidea",   categoria: "natura"   },
    { parola: "Ospedale",   categoria: "luoghi"   },
    { parola: "Osteria",    categoria: "luoghi"   },
  ],
  P: [
    { parola: "Panda",       categoria: "animali"  },
    { parola: "Pappagallo",  categoria: "animali"  },
    { parola: "Pecora",      categoria: "animali"  },
    { parola: "Pinguino",    categoria: "animali"  },
    { parola: "Pollo",       categoria: "animali"  },
    { parola: "Pesca",       categoria: "frutta"   },
    { parola: "Pera",        categoria: "frutta"   },
    { parola: "Prugna",      categoria: "frutta"   },
    { parola: "Pane",        categoria: "cibi"     },
    { parola: "Pasta",       categoria: "cibi"     },
    { parola: "Prosciutto",  categoria: "cibi"     },
    { parola: "Piatto",      categoria: "oggetti"  },
    { parola: "Penna",       categoria: "oggetti"  },
    { parola: "Pallone",     categoria: "oggetti"  },
    { parola: "Portafoglio", categoria: "oggetti"  },
    { parola: "Panettiere",  categoria: "mestieri" },
    { parola: "Pompiere",    categoria: "mestieri" },
    { parola: "Pilota",      categoria: "mestieri" },
    { parola: "Pino",        categoria: "natura"   },
    { parola: "Palma",       categoria: "natura"   },
    { parola: "Piazza",      categoria: "luoghi"   },
    { parola: "Porto",       categoria: "luoghi"   },
  ],
  Q: [
    { parola: "Quaglia",    categoria: "animali"  },
    { parola: "Quercia",    categoria: "natura"   },
    { parola: "Quarzo",     categoria: "natura"   },
    { parola: "Quadro",     categoria: "oggetti"  },
    { parola: "Quaderno",   categoria: "oggetti"  },
    { parola: "Quotidiano", categoria: "oggetti"  },
    { parola: "Quintale",   categoria: "oggetti"  },
    { parola: "Quiche",     categoria: "cibi"     },
    { parola: "Quartiere",  categoria: "luoghi"   },
    { parola: "Questura",   categoria: "luoghi"   },
    { parola: "Quota",      categoria: "luoghi"   },
  ],
  R: [
    { parola: "Rondine",     categoria: "animali"  },
    { parola: "Riccio",      categoria: "animali"  },
    { parola: "Rana",        categoria: "animali"  },
    { parola: "Rospo",       categoria: "animali"  },
    { parola: "Rinoceronte", categoria: "animali"  },
    { parola: "Radicchio",   categoria: "verdure"  },
    { parola: "Rapa",        categoria: "verdure"  },
    { parola: "Rucola",      categoria: "verdure"  },
    { parola: "Rasoio",      categoria: "oggetti"  },
    { parola: "Radio",       categoria: "oggetti"  },
    { parola: "Ragioniere",  categoria: "mestieri" },
    { parola: "Receptionist",categoria: "mestieri" },
    { parola: "Rovere",      categoria: "natura"   },
    { parola: "Rosmarino",   categoria: "natura"   },
    { parola: "Rosa",        categoria: "natura"   },
    { parola: "Ruscello",    categoria: "natura"   },
    { parola: "Ristorante",  categoria: "luoghi"   },
    { parola: "Rimessa",     categoria: "luoghi"   },
    { parola: "Regione",     categoria: "luoghi"   },
  ],
  S: [
    { parola: "Serpente",    categoria: "animali"  },
    { parola: "Scoiattolo",  categoria: "animali"  },
    { parola: "Struzzo",     categoria: "animali"  },
    { parola: "Salmone",     categoria: "animali"  },
    { parola: "Scimmia",     categoria: "animali"  },
    { parola: "Susina",      categoria: "frutta"   },
    { parola: "Spinaci",     categoria: "verdure"  },
    { parola: "Sedano",      categoria: "verdure"  },
    { parola: "Scarpa",      categoria: "oggetti"  },
    { parola: "Sedia",       categoria: "oggetti"  },
    { parola: "Specchio",    categoria: "oggetti"  },
    { parola: "Sofà",        categoria: "oggetti"  },
    { parola: "Sarto",       categoria: "mestieri" },
    { parola: "Scultore",    categoria: "mestieri" },
    { parola: "Salice",      categoria: "natura"   },
    { parola: "Sambuco",     categoria: "natura"   },
    { parola: "Stadio",      categoria: "luoghi"   },
    { parola: "Supermercato",categoria: "luoghi"   },
    { parola: "Scuola",      categoria: "luoghi"   },
    { parola: "Strada",      categoria: "luoghi"   },
  ],
  T: [
    { parola: "Topo",       categoria: "animali"  },
    { parola: "Tacchino",   categoria: "animali"  },
    { parola: "Tricheco",   categoria: "animali"  },
    { parola: "Tigre",      categoria: "animali"  },
    { parola: "Tartaruga",  categoria: "animali"  },
    { parola: "Tasso",      categoria: "animali"  },
    { parola: "Tavolo",     categoria: "oggetti"  },
    { parola: "Tazza",      categoria: "oggetti"  },
    { parola: "Telefono",   categoria: "oggetti"  },
    { parola: "Trapano",    categoria: "oggetti"  },
    { parola: "Tenda",      categoria: "oggetti"  },
    { parola: "Tecnico",    categoria: "mestieri" },
    { parola: "Traduttore", categoria: "mestieri" },
    { parola: "Tiglio",     categoria: "natura"   },
    { parola: "Teatro",     categoria: "luoghi"   },
    { parola: "Torre",      categoria: "luoghi"   },
    { parola: "Treno",      categoria: "veicoli"  },
    { parola: "Tram",       categoria: "veicoli"  },
  ],
  U: [
    { parola: "Uccello",    categoria: "animali"  },
    { parola: "Usignolo",   categoria: "animali"  },
    { parola: "Upupa",      categoria: "animali"  },
    { parola: "Urogallo",   categoria: "animali"  },
    { parola: "Uva",        categoria: "frutta"   },
    { parola: "Uvetta",     categoria: "cibi"     },
    { parola: "Uovo",       categoria: "cibi"     },
    { parola: "Uniforme",   categoria: "oggetti"  },
    { parola: "Utensile",   categoria: "oggetti"  },
    { parola: "Urologo",    categoria: "mestieri" },
    { parola: "Urbanista",  categoria: "mestieri" },
    { parola: "Ulivo",      categoria: "natura"   },
    { parola: "Ufficio",    categoria: "luoghi"   },
    { parola: "Uscita",     categoria: "luoghi"   },
  ],
  V: [
    { parola: "Volpe",        categoria: "animali"  },
    { parola: "Vipera",       categoria: "animali"  },
    { parola: "Vespa",        categoria: "animali"  },
    { parola: "Vulture",      categoria: "animali"  },
    { parola: "Verdura",      categoria: "verdure"  },
    { parola: "Vite",         categoria: "natura"   },
    { parola: "Viola",        categoria: "natura"   },
    { parola: "Vigna",        categoria: "natura"   },
    { parola: "Valle",        categoria: "natura"   },
    { parola: "Valigia",      categoria: "oggetti"  },
    { parola: "Vasca",        categoria: "oggetti"  },
    { parola: "Ventilatore",  categoria: "oggetti"  },
    { parola: "Vaso",         categoria: "oggetti"  },
    { parola: "Violino",      categoria: "oggetti"  },
    { parola: "Veterinario",  categoria: "mestieri" },
    { parola: "Vigile",       categoria: "mestieri" },
    { parola: "Villaggio",    categoria: "luoghi"   },
  ],
  Z: [
    { parola: "Zebra",    categoria: "animali"  },
    { parola: "Zanzara",  categoria: "animali"  },
    { parola: "Zucchina", categoria: "verdure"  },
    { parola: "Zucca",    categoria: "verdure"  },
    { parola: "Zaino",    categoria: "oggetti"  },
    { parola: "Zappa",    categoria: "oggetti"  },
    { parola: "Zerbino",  categoria: "oggetti"  },
    { parola: "Zucchero", categoria: "cibi"     },
    { parola: "Zampone",  categoria: "cibi"     },
    { parola: "Zinnia",   categoria: "natura"   },
    { parola: "Zolfo",    categoria: "natura"   },
    { parola: "Zoo",      categoria: "luoghi"   },
    { parola: "Zona",     categoria: "luoghi"   },
  ],
};
